version: 0.2
phases: 
  install: 
    runtime-versions: 
      python: 3.11
    commands: 
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib
  build:  
    commands: 
      - echo "Zip the deployment packages"
      - cd lib
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - zip -g deployment_package.zip lambda_function.py
  post_build: 
    commands:
      - echo "Uploading to s3 Location"
      - aws s3 cp deployment_package.zip s3://lambda-builds-zip-folder/
      - echo "updating lambda function via s3 bucket"
      - aws lambda update-function-code --funtion-name  lambda-assign3 --s3-bucket lambda-builds-zip-folder --s3-key deployment_package.zip
      - echo "Deployment Done successfully!!!"